name: Elixir
on: push
env:
  VIPS_VERSION: 8.10.2
jobs:
  linux:
    runs-on: ubuntu-latest
    name: Test - Linux OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - elixir: 1.9.x
            otp: 22.x
          - elixir: 1.10.x
            otp: 23.x
          - elixir: 1.12.x
            otp: 24.x
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Checkout vix
        uses: actions/checkout@v2

      - name: Install vips dependencies
        run: sudo apt-get install build-essential libxml2-dev libfftw3-dev libmagickwand-dev libopenexr-dev liborc-0.4-0 gobject-introspection libgsf-1-dev libglib2.0-dev liborc-0.4-dev curl

      - name: Cache vips
        uses: actions/cache@v2
        id: vips-cache
        with:
          path: vips
          key: ${{ runner.os }}-vips-${{ env.VIPS_VERSION }}

      - name: Download and compile vips
        if: steps.vips-cache.outputs.cache-hit != 'true'
        run: |
          mkdir vips
          curl -L https://github.com/libvips/libvips/releases/download/v${{ env.VIPS_VERSION }}/vips-${{ env.VIPS_VERSION }}.tar.gz | tar xzC vips --strip-components=1
          cd vips
          ./configure
          make

      - name: Install vips
        run: |
          cd vips
          sudo make install
          sudo ldconfig -v

      - name: Install Dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile --force --warnings-as-errors

      - name: Run Tests
        run: mix test

  check_format:
    runs-on: ubuntu-latest
    name: Check format
    strategy:
      matrix:
        include:
          - elixir: 1.12.x
            otp: 24.x
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Checkout vix
        uses: actions/checkout@v2

      - name: Check format
        run: mix format --check-formatted
